on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    permissions:
      contents: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Install dependencies
        run: |
          composer install
      - name: Tests
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: ./vendor/bin/pest
      - name: Lint
        run: ./vendor/bin/pint --test
